--view use out join or left join
--select * from somewhere minus select *
CREATE VIEW VIEW_USER_INFORMATION AS SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, 
U.MONTY_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, HC.CITY_NAME, HC.STATE_NAME, HC.COUNTRY_NAME, CC.CITY_NAME, 
CC.STATE_NAME, CC.COUNTRY_NAME, P.INSTITUTION, E.PROGRAM_YEAR, P.CONCENTRATION, P.DEGREE 
FROM USER U, CITIES HC, CITIES CC, USER_CURRENT_CITY CUCI, USER_HOMETOWN_CITY HOMECI, PROGRAM P, EDUCATION E 
WHERE U.USER_ID=CUCI.USER_ID AND U.USER_ID=HOMECI.USER_ID AND CC.CITY_ID=CUCI.CURRENT_CITY_ID AND 
CC.CITY_ID=HOMECI.HOMETOWN_CITY_ID AND U.USER_ID=E.USER_ID AND P.PROGRAM_ID=E.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS SELECT USER1_ID, USER2_ID FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS SELECT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK 
FROM ALBUMS A, PHOTOS P WHERE A.ALBUM_ID=P.ALBUM_ID;